### ISSUE TITLE
[Help] Can you explain how to run the project?

### ISSUE THREAD

**Issue by SocialKitLtd** [DhruvinV/VisualComputing#1]
Hey there,

Can you explain how to run the project?

Thanks!

**Comment by DhruvinV** [comment]
Hey guys,

An additional Kivy application is required (not uploaded on GitHub), to run the algorithms. It requires binary masks for the case of inpainting and other images, as mentioned in the papers. Due to specific university guidelines on completed coursework, I cannot make it public. You can reach me at [dhruvin.vekariya@mail.utoronto.ca](url) if you want to chat further about this.  

Cheers,
Dhruvin
